### ISSUE TITLE
menu.add_size should be positive

### ISSUE THREAD

**Issue by iddm** [worron/redflat#3] opened 2017-10-14 07:30 UTC
When migrating from old version (2 years old) redflat to new one (latest available today) there are errors caused by invalid __newindex in the wibox in this line (redflat/menu.lua:594):

    _menu.wibox.height = _menu.add_size

The issue is because we have set `add_size` to 0 before. I don't know exactly why this happens but setting it to any positive integer (>= 1.0) fixes the error. Probably, something has changed within lua or the wibox itself in newest packages (I am using archlinux so everything is the up-to-date).

**Comment by worron** [comment] 2017-10-14 15:55
Sorry, can't reproduce on my system. But I added minor fix for this anyway, check if it solving the problem.

**Comment by iddm** [comment] 2017-10-14 16:28
I have done almost the same thing to fix it, it works this way.

**Closed as completed** 2017-10-14 16:46 UTC
